// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// myQQNormIntern
NumericMatrix myQQNormIntern(NumericVector mySeq, double myMean, double mySd, double lengthX, int n_sim);
RcppExport SEXP StMoSim_myQQNormIntern(SEXP mySeqSEXP, SEXP myMeanSEXP, SEXP mySdSEXP, SEXP lengthXSEXP, SEXP n_simSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type mySeq(mySeqSEXP );
        Rcpp::traits::input_parameter< double >::type myMean(myMeanSEXP );
        Rcpp::traits::input_parameter< double >::type mySd(mySdSEXP );
        Rcpp::traits::input_parameter< double >::type lengthX(lengthXSEXP );
        Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP );
        NumericMatrix __result = myQQNormIntern(mySeq, myMean, mySd, lengthX, n_sim);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
